[package]
name = "math"
version = "0.1.0"
edition = "2021"

[lib]
name = "math"

[dependencies]
num-traits = "0.2"
thiserror = "1.0"
typenum = "1.17.0"
fixed = "1.27.0"
fixed-exp = { path = "../fixed-exp" }
bn = { path = "../bn" }
