[package]
name = "stabble-stable-swap"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "*"
anyhow = "1.0.86"
rust_decimal = "1.26.1"
jupiter-amm-interface = { git = "https://github.com/jup-ag/jupiter-amm-interface.git", branch = "feat/stabble" }
spl-token = { version = "*", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "*", features = ["no-entrypoint"] }
bn = { path = "../../libraries/bn" }
math = { path = "../../libraries/math" }
stabble-vault = { path = "../vault" }
